from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, ConfigDict

class ProductBase(BaseModel):
    name: str = Field(..., min_length=2, max_length=255, examples=["AI Leather Jacket"])
    description: Optional[str] = Field(None, examples=["A cool jacket generated by AI."])
    price: int = Field(..., ge=0, examples=[150000])
    stock_quantity: int = Field(..., ge=0, examples=[10])
    category: Optional[str] = Field(None, examples=["Outerwear"])
    image_url: Optional[str] = None

class ProductCreate(ProductBase):
    pass

class ProductUpdate(ProductBase):
    name: Optional[str] = None
    price: Optional[int] = None
    stock_quantity: Optional[int] = None

class ProductResponse(ProductBase):
    id: int
    in_stock: bool
    created_at: datetime
    updated_at: datetime
    # embedding과 deleted_at은 제외하여 응답 크기 최적화

    model_config = ConfigDict(from_attributes=True)

class SearchQuery(BaseModel):
    query: str = Field(..., min_length=1, description="검색어")
    min_price: Optional[int] = Field(None, ge=0, description="최소 가격")
    max_price: Optional[int] = Field(None, ge=0, description="최대 가격")
    category: Optional[str] = Field(None, description="카테고리")    